---
- name: Install custom DHC tools
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    install_recommends: yes
  vars:
    packages:
    - xfsprogs
    - etcd-client
    - screen
    - tmux
    - mc
    - inetutils-traceroute
    - tcptraceroute
    - htop
    - ctop
    - iotop
    - iftop
    - nmap

- name: disable apparmor
  systemd:
    name: apparmor
    enabled: no
    masked: yes

- name: disable rsyslog because we only need systemd-journald
  systemd:
    name: rsyslog
    enabled: no
    masked: yes

- name: disable apt-daily.timer
  systemd:
    name: apt-daily.timer
    enabled: no
    masked: yes

- name: disable apt-daily-upgrade.timer
  systemd:
    name: apt-daily-upgrade.timer
    enabled: no
    masked: yes

- name: disable motd-news.timer
  systemd:
    name: motd-news.timer
    enabled: no
    masked: yes

- name: disable motd-news.service
  systemd:
    name: motd-news.service
    enabled: no
    masked: yes

# fix rp_filter to value 1, otherwise calico won't work.
# see https://github.com/kubernetes-sigs/kind/issues/891
- name: fix rp_filter in /etc/sysctl.d/10-network-security.conf
  replace:
    path: /etc/sysctl.d/10-network-security.conf
    regexp: 'rp_filter=2'
    replace: 'rp_filter=1'

- name: disable apparmor
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=""'
    replace: 'GRUB_CMDLINE_LINUX="apparmor=0"'

- name: update grub config
  shell: update-grub

- name: Creates unit file directory
  file:
    path: /etc/systemd/system/ssh.service.d
    state: directory

- name: Create ssh boot order drop in file
  template:
    dest: /etc/systemd/system/ssh.service.d/boot-order.conf
    src: files/etc/systemd/system/ssh.service.d/boot-order.conf

- name: set Ubuntu pw
  command: |-
    echo 'ubuntu:ubuntu' | chpasswd -c SHA512

- name: Create cert dir
  file:
    state: directory
    path: "/usr/local/share/ca-certificates/kubernetes"
    owner: root
    mode: "0755"

- name: Copy certs
  copy:
    src: "files/certificates/{{ item }}"
    dest: "/usr/local/share/ca-certificates/kubernetes/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
  - "CorpDir.net-AMERICAS-Issuing-CA01_2018.crt"
  - "CorpDir.net-AMERICAS-Issuing-CA02_2018.crt"
  - "CorpDir.net-APAC-Issuing-CA01_2018.crt"
  - "CorpDir.net-APAC-Issuing-CA02_2018.crt"
  - "CorpDir.net-Corp-Issuing-CA01-G2_2026.crt"
  - "CorpDir.net-Corp-Issuing-CA02-G2_2026.crt"
  - "CorpDir.net-EMEA-Issuing-CA01_2018.crt"
  - "CorpDir.net-EMEA-Issuing-CA02_2018.crt"
  - "CorpDir.net-Ext-Issuing-CA01-G2_2026.crt"
  - "CorpDir.net-Intermediate-CA01_2018.crt"
  - "Corp-Root-CA_2021.crt"
  - "Corp-Root-CA-G2_2036.crt"
  - "hybridcloud-ca.crt"

- name: Update ca certs
  command: |-
    update-ca-certificates
