name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-18.04

        steps:
        - uses: actions/checkout@v1
        - name: Install prereqs
          run: ./install-prereqs.sh
      - - name: Execute packer
          run: ./build.sh
