name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-18.04

        steps:
        - uses: actions/checkout@v1
        - uses: docker://sbueringer/packer:latest
        - name: Execute packer
          run: ./build.sh
